Add LlamaHub load component
ml6team/fondant-usecase-RAG pull request #30
Opened 2023-11-30 13:41 UTC by RobbeSneyders

This PR adds a load component that can load data using any LlamaHub loader.

Opening as a draft PR for now since it uses the dev release.

2023-11-30 16:45 UTC, RobbeSneyders commented
Ready to be reviewed and merge, since 0.8.dev2 is in a state that we can start merging updated PRs here.

2023-12-01 13:42 UTC, Hakimovich99 commented on src/components/load_with_llamahub/src/main.py
> +        if self.column_name_mapping:
But self.column_name_mapping is never defined?

2023-12-01 13:51 UTC, Hakimovich99 requested changes

2023-12-01 13:51 UTC, Hakimovich99 commented on src/components/load_with_llamahub/src/main.py
> +        if self.column_name_mapping:
But self.column_name_mapping is never defined?

2023-12-04 15:17 UTC, RobbeSneyders commented on src/components/load_with_llamahub/src/main.py
> +        for field_name, field in self.spec.produces.items():
Also removed.

2023-12-04 15:18 UTC, RobbeSneyders commented
Both your comments should be addressed @Hakimovich99. Retested the component, still works :+1:

2023-12-04 15:58 UTC, Hakimovich99 approved these changes

2023-12-04 15:58 UTC, merged